# Site settings
title: Kausar Patherya
email: 
description: "I like to write, design, code, and share some of the cool projects I'm working on. From AI to CrossFit, I'm all about pushing limits. This blog tries to capture that. I try not to be boring."
baseurl: ""
url: "https://www.kausarpatherya.com"
github_username: kpath1999
linkedin_username:  k-path
youtube_username: gatechai
spotify_username: gatechai

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  math_engine: mathjax